/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiBackgroundRouteImport } from './routes/ai-background'
import { Route as AiEnhanceRouteImport } from './routes/ai-enhance'
import { Route as AiVoiceRouteImport } from './routes/ai-voice'
import { Route as AvatarRouteImport } from './routes/avatar'
import { Route as CameraRouteImport } from './routes/camera'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProjectsRouteImport } from './routes/projects'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiBackgroundRoute = AiBackgroundRouteImport.update({
  id: '/ai-background',
  path: '/ai-background',
  getParentRoute: () => rootRouteImport,
} as any)
const AiEnhanceRoute = AiEnhanceRouteImport.update({
  id: '/ai-enhance',
  path: '/ai-enhance',
  getParentRoute: () => rootRouteImport,
} as any)
const AiVoiceRoute = AiVoiceRouteImport.update({
  id: '/ai-voice',
  path: '/ai-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarRoute = AvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraRoute = CameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-background': typeof AiBackgroundRoute
  '/ai-enhance': typeof AiEnhanceRoute
  '/ai-voice': typeof AiVoiceRoute
  '/avatar': typeof AvatarRoute
  '/camera': typeof CameraRoute
  '/editor': typeof EditorRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-background': typeof AiBackgroundRoute
  '/ai-enhance': typeof AiEnhanceRoute
  '/ai-voice': typeof AiVoiceRoute
  '/avatar': typeof AvatarRoute
  '/camera': typeof CameraRoute
  '/editor': typeof EditorRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-background': typeof AiBackgroundRoute
  '/ai-enhance': typeof AiEnhanceRoute
  '/ai-voice': typeof AiVoiceRoute
  '/avatar': typeof AvatarRoute
  '/camera': typeof CameraRoute
  '/editor': typeof EditorRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-background'
    | '/ai-enhance'
    | '/ai-voice'
    | '/avatar'
    | '/camera'
    | '/editor'
    | '/home'
    | '/profile'
    | '/projects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-background'
    | '/ai-enhance'
    | '/ai-voice'
    | '/avatar'
    | '/camera'
    | '/editor'
    | '/home'
    | '/profile'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/ai-background'
    | '/ai-enhance'
    | '/ai-voice'
    | '/avatar'
    | '/camera'
    | '/editor'
    | '/home'
    | '/profile'
    | '/projects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiBackgroundRoute: typeof AiBackgroundRoute
  AiEnhanceRoute: typeof AiEnhanceRoute
  AiVoiceRoute: typeof AiVoiceRoute
  AvatarRoute: typeof AvatarRoute
  CameraRoute: typeof CameraRoute
  EditorRoute: typeof EditorRoute
  HomeRoute: typeof HomeRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-background': {
      id: '/ai-background'
      path: '/ai-background'
      fullPath: '/ai-background'
      preLoaderRoute: typeof AiBackgroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-enhance': {
      id: '/ai-enhance'
      path: '/ai-enhance'
      fullPath: '/ai-enhance'
      preLoaderRoute: typeof AiEnhanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-voice': {
      id: '/ai-voice'
      path: '/ai-voice'
      fullPath: '/ai-voice'
      preLoaderRoute: typeof AiVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar': {
      id: '/avatar'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof AvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera': {
      id: '/camera'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof CameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiBackgroundRoute: AiBackgroundRoute,
  AiEnhanceRoute: AiEnhanceRoute,
  AiVoiceRoute: AiVoiceRoute,
  AvatarRoute: AvatarRoute,
  CameraRoute: CameraRoute,
  EditorRoute: EditorRoute,
  HomeRoute: HomeRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
